### ISSUE TITLE
error on mural_train 

### ISSUE THREAD

**Issue by fightyy** [CaiLiLab/MuRaL#11]
when I try to run example data under wsl2 on windows.
`singularity exec --nv /home/yangy/packages/linux/mural_v1.1.1.sif mural_train 
--ref_genome data/seq.fa --train_data data/training.sorted.bed --experiment_name example1`

I got an error
`Traceback (most recent call last):                                                                                              
File "/opt/conda/bin/mural_train", line 7, in <module>                                                                                    main()                                                                                                          
File "/opt/conda/lib/python3.8/site-packages/MuRaL/run_train_raytune.py", line 551, in main                                                                 nvmlInit()                                                                                                        
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1450, in nvmlInit                                                                     nvmlInitWithFlags(0)  

​                                                                                                 
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1440, in nvmlInitWithFlags                                                                _nvmlCheckReturn(ret)                                                                                                  
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn                                                                 raise NVMLError(ret)                                                                                                  pynvml.nvml.NVMLError_DriverNotLoaded: Driver Not LoadedTraceback (most recent call last):                                                                                              
File "/opt/conda/bin/mural_train", line 7, in <module>                                                                                    main()                                                                                                          
File "/opt/conda/lib/python3.8/site-packages/MuRaL/run_train_raytune.py", line 551, in main                                                                 nvmlInit()                                                                                                        
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1450, in nvmlInit                                                                     nvmlInitWithFlags(0)                                                                                                   
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1440, in nvmlInitWithFlags                                                                _nvmlCheckReturn(ret)                                                                                                  
File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn                                                                 raise NVMLError(ret)                                                                                                  pynvml.nvml.NVMLError_DriverNotLoaded: Driver Not Loaded `

In fact, my cuda version and driver are as follows：
NVIDIA-SMI 515.43.01  Driver Version: 516.01    CUDA Version: 11.7   

How can I deal with it. thank you

**Comment by JuseTiZ** [comment]
Please check if your device has a GPU. If it does, ensure that the **nvidia driver** is properly installed. For more details, you can refer to this link:

https://forums.developer.nvidia.com/t/pynvml-nvml-nvmlerror-drivernotloaded-driver-not-loaded/290093

**Comment by fightyy** [comment]
My computer's GPU is a 3080. My driver version is 516.0, and the CUDA version is 11.6. The driver works correctly and can run CUDA in torch 1.12.0. However, it seems that running mural_train in Singularity is not successful. Is it because my driver version and the CUDA version in the Mural image are incompatible?

**Comment by fightyy** [comment]
Thanks for your replying!
My computer's GPU is a 3080. My driver version is 516.0, and the CUDA version is 11.6. The driver works correctly and can run CUDA in torch 1.12.0. However, it seems that running `mural_train` in Singularity is not successful. Is it because my driver version and the CUDA version in the Mural image are incompatible?

**Comment by JuseTiZ** [comment]
> My computer's GPU is a 3080. My driver version is 516.0, and the CUDA version is 11.6.

@fightyy 

It appears that the CUDA version 11.6 you are using is incompatible with the version of PyTorch (1.10.2) included in the MuRaL container. Unfortunately, PyTorch 1.10.2 does not support CUDA 11.6; you would need at least PyTorch 1.12.0 for that.

I apologize for any inconvenience this may have caused. You might consider creating another environment with an earlier version of CUDA, such as CUDA 11.3. Alternatively, you can install MuRaL locally and use it with your current PyTorch version.

Additionally, you can verify if Singularity is able to properly access the GPU information. This can help determine whether the issue is related to Singularity itself or to version compatibility:

`singularity exec --nv /home/yangy/packages/linux/mural_v1.1.1.sif nvidia-smi`

**Comment by fightyy** [comment]
Thank you. Following your instruction, I found that in WSL2, to use the GPU with Singularity, the command needs to add `--nvccli` after `--nv`. This time, the GPU was successfully used, but another error occurred. I will give up using Singularity.

Traceback (most recent call last):                                                                                  

File "/opt/conda/bin/mural_train", line 7, in <module> main()                                                                                              

File "/opt/conda/lib/python3.8/site-packages/MuRaL/run_train_raytune.py", line 585, in main                                                      ray.init(num_cpus=ray_ncpus, num_gpus=ray_ngpus, dashboard_host="0.0.0.0")                                                            

File "/opt/conda/lib/python3.8/site-packages/ray/worker.py", line 696, in init_global_node = ray.node.Node(                                                                                   

File "/opt/conda/lib/python3.8/site-packages/ray/node.py", line 205, in __init__                                                           self.start_ray_processes()                                                                                    

File "/opt/conda/lib/python3.8/site-packages/ray/node.py", line 820, in start_ray_processes                                                      ray.services.determine_plasma_store_config(                                                                            

File "/opt/conda/lib/python3.8/site-packages/ray/services.py", line 1610, in determine_plasma_store_config                                              shm_avail = ray.utils.get_shared_memory_bytes()                                                                          

File "/opt/conda/lib/python3.8/site-packages/ray/utils.py", line 641, in get_shared_memory_bytes                                                   shm_fd = os.open("/dev/shm", os.O_RDONLY)                                                                            

FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'

**Comment by fightyy** [comment]
Thank you. Following your instruction, I found that in WSL2, to use the GPU with Singularity, the command needs to add `--nvccli` after `--nv`. This time, the bug above was fixed, but another error occurred. I will give up using Singularity.
Traceback (most recent call last):                                                                                  

File "/opt/conda/bin/mural_train", line 7, in <module> main()                                                                                              

File "/opt/conda/lib/python3.8/site-packages/MuRaL/run_train_raytune.py", line 585, in main                                                      ray.init(num_cpus=ray_ncpus, num_gpus=ray_ngpus, dashboard_host="0.0.0.0")                                                            

File "/opt/conda/lib/python3.8/site-packages/ray/worker.py", line 696, in init_global_node = ray.node.Node(                                                                                   

File "/opt/conda/lib/python3.8/site-packages/ray/node.py", line 205, in __init__                                                           self.start_ray_processes()                                                                                    

File "/opt/conda/lib/python3.8/site-packages/ray/node.py", line 820, in start_ray_processes                                                      ray.services.determine_plasma_store_config(                                                                            

File "/opt/conda/lib/python3.8/site-packages/ray/services.py", line 1610, in determine_plasma_store_config                                              shm_avail = ray.utils.get_shared_memory_bytes()                                                                          

File "/opt/conda/lib/python3.8/site-packages/ray/utils.py", line 641, in get_shared_memory_bytes                                                   shm_fd = os.open("/dev/shm", os.O_RDONLY)                                                                            

FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm'

**Comment by JuseTiZ** [comment]
The issue is likely because the shared memory directory `/dev/shm` is not mounted or accessible in your WSL2 environment.

I'm not sure if this problem will persist even if you install MuRaL locally. You could try creating this directory or changing the path to an existing one. To create and mount `/dev/shm`, you can use the following commands:

```
sudo mkdir /dev/shm
sudo mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=2G tmpfs /dev/shm
```

The situation of the following issue is similar, maybe you can also refer to it:

https://github.com/xai-org/grok-1/issues/255

**Comment by fightyy** [comment]
谢谢，当我挂载`/dev/shm`后用`df -h /dev/shm`,结果是

`Filesystem      Size  Used Avail Use% Mounted on                                                                                                                                                    tmpfs           2.0G     0  2.0G   0% /run/shm` 

似乎在wsl2里系统将`/dev/shm`链接到`/run/shm` ，于是我在singularity的命令里加上了`-B /dev/shm:/dev/shm`to bind mount the `/run/shm` directory from the host into the same location within the container. 现在成功的运行了。完整的命令如下：

`singularity exec --nv --nvccli -B /run/shm:/run/shm /home/yangy/packages/linux/mural_v1.1.1.sif mural_train --ref_genome data/seq.fa --train_data data/training.sorted.bed --experiment_name example1`



After mounting `/dev/shm`, I used `df -h /dev/shm`, and the result was:

```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2.0G     0  2.0G   0% /run/shm
```

It seems that in WSL2, the system links `/dev/shm` to `/run/shm`. So, I added `-B /run/shm:/run/shm` to the Singularity command to bind mount the `/run/shm` directory from the host into the same location within the container. Now it runs successfully. The complete command is:

```
singularity exec --nv --nvccli -B /run/shm:/run/shm /home/yangy/packages/linux/mural_v1.1.1.sif mural_train --ref_genome data/seq.fa --train_data data/training.sorted.bed --experiment_name example1
```

**Comment by fightyy** [comment]
Thank you！After mounting `/dev/shm`, I used `df -h /dev/shm`, and the result was:

```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2.0G     0  2.0G   0% /run/shm
```

It seems that in WSL2, the system links `/dev/shm` to `/run/shm`. So, I added `-B /run/shm:/run/shm` to the Singularity command to bind mount the `/run/shm` directory from the host into the same location within the container. Now it runs successfully. The complete command is:

```
singularity exec --nv --nvccli -B /run/shm:/run/shm /home/yangy/packages/linux/mural_v1.1.1.sif mural_train --ref_genome data/seq.fa --train_data data/training.sorted.bed --experiment_name example1
```
