### ISSUE TITLE
use singularity under CPU

### ISSUE THREAD

**Issue by bighawkin** [CaiLiLab/MuRaL#6]
because of error when use GPU，so i try to use only GPU. i have no idea, please give me some advice.

The run:
singularity exec  ~/software/mural_v1.1.0.sif  mural_train --ref_genome data/seq.fa --train_data data/training.sorted.bed --experiment_name example1  > test1.out 2> test1.err

 cat test1.err 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1478, in _LoadNvmlLibrary
    nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/opt/conda/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/mural_train", line 7, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/MuRaL/run_train_raytune.py", line 550, in main
    nvmlInit()
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1433, in nvmlInitWithFlags
    _LoadNvmlLibrary()
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 1480, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

**Comment by bighawkin** [comment]
it has been resolved,thank you

**Comment by cailigd** [comment]
Thanks for letting us know!

If you don't want to use GPUs, you can set the options '--ray_ngpus 0 --gpu_per_trial 0' in the command line.
